version: 2

formatters:
  enable:
    - gofumpt
    - golines
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/KurosawaAngel/beget
    gofumpt:
      module-path: github.com/KurosawaAngel/beget
      extra-rules: true
    golines:
      max-len: 120
      reformat-tags: false
